SystemName: Mockingbird
SystemInitialName: M
Mockingbird: Mockingbird
AccountID: Account ID
Password: Password
Login: Login
Logout: Logout
Welcome: Welcome!
ThisisMockingbird: Mockingbird is one of BTS
LoginFromHere: Login from here.
CurrentPassword: Current Password
NewPassword: New Password
NewPassword2: New Password(Confirm)
ChangePassword: Change Password

Top: Top
Timeline: Timeline
TimelineOf u@User: #{userName u}'s Timeline
MyTasks: My tasks
TasksOf u@User: #{userName u}'s Tasks
CreateNewIssue: Create new issue
Dropdown u@User: #{userName u}

HomeOf u@User: #{userName u}'s Home
