SystemName: Mockingbird
SystemInitialName: M
Mockingbird: Mockingbird
AccountID: Account ID
Password: Password
Login: Login
Logout: Logout
Welcome: Welcome!
ThisisMockingbird: Mockingbird is one of BTS
LoginFromHere: Login from here.
CurrentPassword: Current Password
NewPassword: New Password
NewPassword2: New Password(Confirm)
ChangePassword: Change Password

Top: Top
Timeline: Timeline
TimelineOf u@User: #{userName u}'s Timeline
MyTasks: My tasks
TasksOf u@User: #{userName u}'s Tasks
CreateNewIssue: Create new issue
Dropdown u@User: #{userName u}

Search: Search
Users: Users

Update: Update

Success: Success
Warning: Warning
Error: Error

HomeOf u@User: #{userName u}'s Home

IssueSubject: Subject
IssueDescription: Description
IssueLimitDay: Limit day
IssueLimitTime: Limit time
IssueOpener: Opener
IssueCreated: Created datetime
IssueUpdated: Updated datetime
IssueLimitDatetime: Limit datetime
CreateIssue: Create Issue

SucceedToCreateIssue: Succeed to create a issue
FailureToCreateIssue: Failure to create a issue

AddAllChannel: Add `ALL' channel
AddAnyChannel: Add `ANY' channel
AddEachChannel: Add `EACH' channel
AddMyChannel: Add `MY' channel

Subject v@Issue: #{issueSubject v}

SecondsAgo n@Integer: #{show n}secs
MinutesAgo n@Integer: #{show n}mins
HoursAgo n@Integer: #{show n}hrs
DaysAgo n@Integer: #{show n}days
MonthsAgo n@Integer: #{show n}months
YearsAgo n@Integer: #{show n}years

SearchUser: Search user
UserNameOrIdent: User name or id
CreateGroup: Create group

