SystemName: Mockingbird
SystemInitialName: M
Mockingbird: Mockingbird
AccountID: アカウント
Password: パスワード
Login: ログイン
Logout: ログアウト
Welcome: ようこそ!
ThisisMockingbird: Mockingbirdタスク管理システム
LoginFromHere: ここからログインしてください
CurrentPassword: 現在のパスワード
NewPassword: 新しいパスワード
NewPassword2: 新しいパスワード(確認)
ChangePassword: パスワード変更

Top: トップ
Timeline: はなす
TimelineOf u@User: #{userName u}のタイムライン
MyTasks: やる
TasksOf u@User: #{userName u}のやること
Create: つくる
CreateNewIssue: タスクをきめよう
ChoiceMembers: やってもらう
CreateNewSelfIssue: じぶんでやる
CreateNewMyIssue: じぶんのあたらしいタスクをつくる
Dropdown u@User: #{userName u}

Search: さがす
Users: ユーザ

Update: 更新する

Success: 成功
Warning: 警告
Error: エラー

HomeOf u@User: #{userName u}のホーム

IssueSubject: 課題
SimpleAndClarity: 簡潔に分かりやすく
CreateTaskForYourself: 自分でやること
IssueDescription: 内容
InDetail: くわしく
IssueLimitDay: 期限日
IssueLimitTime: 期限時刻
IssueOpener: 起票者
IssueScope: 公開/非公開
IssueCreated: 作成日
IssueUpdated: 更新日
IssueLimitDatetime: 期限
CreateIssue: 起票する
CloneIssue: テンプレとしてつかう
CloneIssueShort: コピー

PRIVATE: 非公開
PUBLIC: 公開

SucceedToCreateIssue: 起票に成功しました
FailureToCreateIssue: 起票に失敗しました

UpdateChannel: チャネル更新
AddChannel: チャンネルをつくる
AddChannelShort: チャンネル
AddAllChannel: 「みんな」がやる
AddAllChannelShort: みんな
AddAnyChannel: 「だれか」がやる
AddAnyChannelShort: だれか
AddEachChannel: 「それぞれ」でやる
AddEachChannelShort: それぞれ
AddMyChannel: 「じぶん」でやる
AddMyChannelShort: じぶん
ALL: みんな
ANY: だれか
EditChannel: 編集
EditIssue: 編集
DeleteIssue: タスクを削除する
DeleteIssueShort: 削除
DeleteChannel: 削除
MatchUsers: 表示されている
CheckUsers: えらんでいる

Subject v@Issue: #{issueSubject v}

SecondsAgo n@Integer: #{show n}秒
MinutesAgo n@Integer: #{show n}分
HoursAgo n@Integer: #{show n}時間
DaysAgo n@Integer: #{show n}日
MonthsAgo n@Integer: #{show n}ヶ月
YearsAgo n@Integer: #{show n}年

SecondsLeft n@Integer: あと#{show n}秒
MinutesLeft n@Integer: あと#{show n}分
HoursLeft n@Integer: あと#{show n}時間
DaysLeft n@Integer: あと#{show n}日
MonthsLeft n@Integer: あと#{show n}ヶ月
YearsLeft n@Integer: あと#{show n}年

SecondsLeftShort n@Integer: #{show n}秒
MinutesLeftShort n@Integer: #{show n}分
HoursLeftShort n@Integer: #{show n}時間
DaysLeftShort n@Integer: #{show n}日
MonthsLeftShort n@Integer: #{show n}ヶ月
YearsLeftShort n@Integer: #{show n}年

SecondsOver n@Integer: #{show n}秒過ぎ
MinutesOver n@Integer: #{show n}分過ぎ
HoursOver n@Integer: #{show n}時間過ぎ
DaysOver n@Integer: #{show n}日過ぎ
MonthsOver n@Integer: #{show n}ヶ月過ぎ
YearsOver n@Integer: #{show n}年過ぎ

SecondsOverShort n@Integer: #{show n}秒
MinutesOverShort n@Integer: #{show n}分
HoursOverShort n@Integer: #{show n}時間
DaysOverShort n@Integer: #{show n}日
MonthsOverShort n@Integer: #{show n}ヶ月
YearsOverShort n@Integer: #{show n}年

SearchUser: やってもらう人をえらぼう
UserNameOrIdent: ユーザ名またはID
CreateGroup: グループをつくる

BacktoIssue: 戻る
CheckAll: 全選択
UncheckAll: 全解除

Thread: そうだんしよう
Comment: わかりやすく
Commenting: コメントする
YourTurn: おねがいします
MyTurn: こちらでやります
Closing: おしまいにする
Reopening: やりなおし
AttachFile: ファイルを添付する
YourTurnShort: やれ
MyTurnShort: やる
ClosingShort: おわり
ReopeningShort: もっかい

GotoThread: そうだんする
CloseTicket: おしまいにする
CloseTicketShort: おしまい
Reply: リプライする
ReplyShort: リプライ
YouCouldnotTouchTheTicket: あなたがおしまいにすることはできません.

YouAreNotOwnerOfThisIssue: あなたが作ったタスクではありません.
YouAreNotMemberOfThisIssue: あなたはこのタスクに関わっていません.
YouAreNotMemberOfThisChannel: あなたはこのチャンネルに関わっていません.
YouDontAssignedThisTicket: あなたはこのチケットにアサインされていません.

SearchResult q@Text: 検索結果 `#{q}'

FollowRequirements u@User: `#{userName u}'のフォローが必要
MyOwnIssues: やること
FollowRequiredIssues: やらせること
PrivateIssues: ひみつ
Private u@User: `#{userName u}'のひみつ

ThisPageIsNotYours: あなたのページではありません.
