SystemName: Mockingbird
SystemInitialName: M
Mockingbird: Mockingbird
AccountID: アカウント
Password: パスワード
Login: ログイン
Logout: ログアウト
Welcome: ようこそ!
ThisisMockingbird: Mockingbird イシュートラッキングシステムです
LoginFromHere: ここからログインしてください
CurrentPassword: 現在のパスワード
NewPassword: 新しいパスワード
NewPassword2: 新しいパスワード(確認)
ChangePassword: パスワード変更

Top: トップ
Timeline: タイムライン
MyTasks: マイタスク
CreateNewIssue: イシュー作成
Dropdown u@User: #{userName u}

HomeOf u@User: #{userName u}のホーム
