SystemName: Mockingbird
SystemInitialName: M
Mockingbird: Mockingbird
AccountID: アカウント
Password: パスワード
Login: ログイン
Logout: ログアウト
Welcome: ようこそ!
ThisisMockingbird: Mockingbirdタスク管理システム
LoginFromHere: ここからログインしてください
CurrentPassword: 現在のパスワード
NewPassword: 新しいパスワード
NewPassword2: 新しいパスワード(確認)
ChangePassword: パスワード変更

Top: トップ
Timeline: タイムライン
TimelineOf u@User: #{userName u}のタイムライン
MyTasks: マイタスク
TasksOf u@User: #{userName u}のタスク
CreateNewIssue: イシュー作成
Dropdown u@User: #{userName u}

HomeOf u@User: #{userName u}のホーム

IssueSubject: 課題
IssueDescription: 内容
IssueLimitDate: 期限
IssueOpener: 起票者
IssueCreatedDay: 作成日
IssueCreatedTime: 作成時刻
IssueUpdatedDay: 更新日
IssueUpdatedTime: 更新時刻
CreateIssue: 起票する
